apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: menychtak/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_HOST
          value: database-service
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres
        - name: DATABASE_NAME
          value: todo
