apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-init-config
data:
  init.sql: |
    CREATE TABLE tasks (
        id SERIAL PRIMARY KEY,
        task TEXT NOT NULL
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: todo
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: init-script
        configMap:
          name: database-init-config
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
