version: '3.8'

services:
  backend:
    build: ./project_to_do_list/backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
    - docker_net

  database:
    build: ./project_to_do_list/database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./project_to_do_list/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
    - docker_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  docker_net:
    driver: bridge
