version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: singlestore/cluster-in-a-box:latest
    ports:
      - "3306:3306"
      - "8080:8080"
    environment:
      - LICENSE_KEY=your_license_key
