version: '3.8'

services:
  frontend:
    build: ./project_to_do_list/frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./project_to_do_list/backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    build: ./project_to_do_list/database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres